version: "3"
services:
    routing:
        image: 172.17.0.1:5000/babeld #dm4tze/babeld/dev
        privileged: true
        network_mode: "host"
        container_name: babeld
        restart: unless-stopped

    dfclient:
        image: 172.17.0.1:5000/dfclient
        restart: unless-stopped
        privileged: true
        network_mode: "host"
        container_name: dfclient
        ports:
            - 65001:65001
        volumes:
          - /etc/dragonfly:/etc/dragonfly
          - $HOME/.small-dragonfly:/root/.small-dragonfly
          - /etc/dragonfly/dfdaemon.yml:/etc/dragonfly/dfdaemon.yml
        command: --registry https://index.docker.io

    supernode:
        image: 172.17.0.1:5000/supernode
        network_mode: "host"
        privileged: true
        container_name: supernode
        ports:
            - 8001:8001 #download Port
            - 8002:8002
        volumes:
            - /home/admin/supernode:/home/admin/supernode
            - /etc/dragonfly/supernode.yml:/etc/dragonfly/supernode.yml
        restart: unless-stopped
        command: --download-port=8001

volumes:
    dbdata:
