version: "3"
services:
    routing:
        image: 172.17.0.1:5000/babeld #dm4tze/babeld/dev
        privileged: true
        network_mode: "host"
        container_name: babeld
        restart: unless-stopped

    dfclient:
        image: 172.17.0.1:5000/dfclient
        restart: unless-stopped
        privileged: true
        network_mode: "host"
        container_name: dfclient
        ports:
            - 65001:65001
        volumes:
          - /etc/dragonfly:/etc/dragonfly
          - $HOME/.small-dragonfly:/root/.small-dragonfly
          - /etc/dragonfly/dfdaemon.yml:/etc/dragonfly/dfdaemon.yml
        command: --registry https://index.docker.io
volumes:
    dbdata:
